version: '3.2'
services:
  legacywebshop:
    image: mavogel/hska-vis-legacywebshop
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    image: mavogel/hska-vis-web-shop-db-image
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  categories:
    container_name: categories
    build:
      context: categories/categories
      dockerfile: Dockerfile
    image: vsys:categories
    ports:
      - "8082:8082"
    networks:
      local_dev_net:
        aliases:
          - categories-service

  products:
    container_name: products
    build:
      context: products/products
      dockerfile: Dockerfile
    image: vsys:products
    ports:
      - "8081:8081"
    networks:
      local_dev_net:
        aliases:
          - products-service

networks:
  local_dev_net:
    driver: bridge
